# @package agent
defaults:
  - simple_sf_agent
_target_: agent.sf_consolidation_params_continuous_agent.SFConsolidationParamsContinuousAgent
consolidation: true # whether to use consolidation for the successor features
name: sf_consolidation_params_continuous

# beakers
beaker_capacity: 2
lr_consolidation: ${train.lr_consolidation}
num_beakers: 5
optimizer_consolidation: sgd # [rmsprop, adam, sgd]
sf_consolidation: true
has_task_params: true
flow_factor: 1
update_consolidation_every_steps: 1
